name: icepyx-examples-image
channels:
  - conda-forge
dependencies:
  - contextily
  - geopandas
  - h5py
  - icepyx
  - lxml
  - matplotlib
  - numpy
  - pandas
  - python=3.9
  - rasterio
  - xarray
  - pip:
    - -r file:requirements.txt
