name: icepyx-examples-image
channels:
  - conda-forge
dependencies:
  - contextily
  - geopandas
  - h5py
  - icepyx
  - lxml
  - matplotlib
  - numpy
  - pandas
  - pip
  - python=3.9
  - rasterio
  - xarray
  - pip:
    - git+https://github.com/ICESAT-2HackWeek/topohack.git#egg=topolib
