name: icepyx-examples-image
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - xarray
  - pandas
  - h5py
  - icepyx
  - rasterio
  - geopandas
  - matplotlib
  - lxml
  - pip:
    - -r file:requirements.txt
