name: Test Building Icepyx Image
on: [pull_request_target]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout files in repo
      uses: actions/checkout@v2

    - name: Test Build
      uses: jupyterhub/repo2docker-action@60c656a681c89b894235972a82a4b4da9beddbb4
      with:
        # FIXME: change to the actual values
        IMAGE_NAME: icepyximg/icepyx-gallery-image
        NO_PUSH: true
